//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Device_Info()
        {
            this.JDJS_WMS_Device_ProgState_Info = new HashSet<JDJS_WMS_Device_ProgState_Info>();
            this.JDJS_WMS_Device_RealTime_Data = new HashSet<JDJS_WMS_Device_RealTime_Data>();
            this.JDJS_WMS_Device_Alarm_History_Table = new HashSet<JDJS_WMS_Device_Alarm_History_Table>();
        }
    
        public int ID { get; set; }
        public string MachNum { get; set; }
        public string IP { get; set; }
        public string MachState { get; set; }
        public int MachType { get; set; }
        public Nullable<int> Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_ProgState_Info> JDJS_WMS_Device_ProgState_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_RealTime_Data> JDJS_WMS_Device_RealTime_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Alarm_History_Table> JDJS_WMS_Device_Alarm_History_Table { get; set; }
    }
}
