//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_Type_Info
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public int BrandID { get; set; }
    
        public virtual JDJS_WMS_Device_Brand_Info JDJS_WMS_Device_Brand_Info { get; set; }
    }
}
